source 'https://rubygems.org'


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.1.4'
# Use sqlite3 as the database for Active Record
gem 'sqlite3'

gem 'rack-cors', :require => 'rack/cors'

gem 'seed-fu'

# API
gem 'rails-api'
gem 'versionist'

# Serialization
gem 'active_model_serializers'

# Authentication
gem 'devise'

gem 'omniauth'
# gem 'omniauth-oauthio', '~> 0.2.0'
gem 'omniauth-oauthio', path: '/Users/jonathan/code/github.com/jgrowl/omniauth-oauthio'

gem 'jwt'

# Authorization
gem 'cancancan', '~> 1.9'

# # bundle exec rake doc:rails generates the API under doc/api.
# gem 'sdoc', '~> 0.4.0',          group: :doc

# Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
gem 'spring',        group: :development

group :development, :test do
  gem 'rspec-rails'
  gem 'pry'
end

# # Use ActiveModel has_secure_password
# # gem 'bcrypt', '~> 3.1.7'
#
# # Use unicorn as the app server
# # gem 'unicorn'
#
# # Use Capistrano for deployment
# # gem 'capistrano-rails', group: :development
#
# # Use debugger
# # gem 'debugger', group: [:development, :test]

